BASE: ['']
TOOLBOX_MODE: "only_test"  # "train_and_test" or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 3e-3
  MODEL_FILE_NAME: PURE_PURE_PURE_PhysMambaSF_SpO2
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                 # Set to True if preprocessing is required
    DATA_FORMAT: NCDHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"  # Update as needed
    CACHED_PATH: "/content/drive/MyDrive/DDCache/PhysMambaSF"     # Path for cached/preprocessed data
    EXP_DATA_NAME: ""
    BEGIN: 0.0                          # Use the first 80% of the dataset for training
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']     # Required for PhysMamba
      DATA_AUG: ['None']                # No augmentation applied
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128                 # Segment video into chunks
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'                  # Haar Cascade for face cropping
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                 # Set to True if preprocessing is required
    DATA_FORMAT: NCDHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"  # Update as needed
    CACHED_PATH: "/content/drive/MyDrive/DDCache/PhysMambaSF"     # Path for cached/preprocessed data
    EXP_DATA_NAME: ""
    BEGIN: 0.8                          # Use the next 20% of the dataset for validation
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']     # Required for PhysMamba
      DATA_AUG: ['None']                # No augmentation applied
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                # Set to True if preprocessing is required
    DATA_FORMAT: NCDHW
    DATA_PATH: "/content/drive/MyDrive/Datasets/Extracted_Datasets/PURE"  # Update as needed
    CACHED_PATH: "/content/drive/MyDrive/DDCache/PhysMambaSF"     # Path for cached/preprocessed data
    EXP_DATA_NAME: ""
    BEGIN: 0.8                          # Use the entire dataset for testing
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']     # Required for PhysMamba
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  NAME: PhysMambaSF
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"              # Options: "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10                     # Evaluation window size in seconds
  MODEL_PATH: "/content/drive/MyDrive/DDCache/PhysMambaSF_SP/TrainedModels/PURE_PURE_PURE_PhysMambaSF_SpO2_Epoch6.pth"
